### ISSUE TITLE
Invalid UUID causes unhandled exception

### ISSUE THREAD

**Issue by ThierryKamber** [pdinklag/MinecraftStats#63] opened 2019-07-15 08:43 UTC
When updating the profile for an invalid UUID, for example due to deletion of the associated account, an exception occurs.

```
updating profile for d4afcce8-fce9-427f-a8e4-780e9aff3148 ...
Traceback (most recent call last):
  File "update.py", line 141, in <module>
    profile = mojang.get_player_profile(uuid)
  File "/var/www/stats.tallcraft.com/html/mojang.py", line 13, in get_player_profile
    profile = json.loads(response.read().decode())
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 159, in <module>
    print('failed to update profile for ' + player['name'] + ' (' + uuid + ')')
KeyError: 'name'
```

**Comment by Trikolon** [comment] 2019-07-15 10:23
Duplicate of #61 I think. But good job on finding out what the cause might be.

**Comment by pdinklag** [comment] 2019-07-15 10:37
Yes, looks like the same as #61. Why do you think the UUID is invalid? Is that just a guess or may it be a good hint?

**Comment by pdinklag** [comment] 2019-07-15 11:01
Closing this, see #61 for updates.

**Closed by pdinklag** 2019-07-15 11:01 UTC
Labels: Bug
